# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['lgu_bag_speed.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['rosbag', 'PyQt5', 'PyQt5.QtCore', 'PyQt5.QtGui', 'PyQt5.QtWidgets'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'numpy',
        'pandas',
        'scipy',
        'scikit-learn',
        'matplotlib',
        'PIL',
        'pillow',
        'cv2',
        'cv-bridge',
        'openpyxl',
        'openai',
        'fastapi',
        'flask',
        'uvicorn',
        'starlette',
        'tornado',
        'aiohttp',
        'jupyter',
        'jupyterlab',
        'ipython',
        'ipykernel',
        'notebook',
        'nicegui',
        'customtkinter',
        'ttkbootstrap',
        'reportlab',
        'PyPDF2',
        'cryptography',
        'paramiko',
        'lxml',
        'beautifulsoup4',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='lgu_bag_speed',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)