    float32 distXRefer  
    float32 distYRefer   
    float32 distZ  
    float32 distXVar    
    float32 distYVar    
    float32 distZVar    

    float32 velX    
    float32 velY    
    float32 velXVar   
    float32 velYVar   
    float32 velAbsX   
    float32 velAbsY    
    float32 velAbsXVar    
    float32 velAbsYVar   

    float32 accelX   
    float32 accelY   
    float32 accelXVar   
    float32 accelYVar    

    float32 existProb        
    float32 RCS              
    float32 length
    float32 width
    float32 height
    float32 lengthVar    
    float32 widthVar    
    float32 heightVar    

    float32 yawAng          
    float32 yawAngVar        
    float32 yawRate
    float32 yawRateVar

    uint8 objID          
    uint8 referPt        
    uint8 meaState     
    uint8 dynFlg 
    uint8 ObjMotionType 
    uint8 ObjMotionDirection         

    uint8 obstProbability  
    uint8 objType    
    uint8 objTypeProp	
    uint8 TGUValid
    
    uint16 lifeCycle    

  
    uint8 isRefPtChange 
    uint8 padding

    float32 distX   
    float32 distY    
    uint32 objUnqID
    float32 yawAngMoved      
    float32 yawAngFilterMoved 

    bool leftBsdFlag
    bool rightBsdFlag
    bool leftLcaFlag
    bool rightLcaFlag

    bool leftDowFlag
    bool rightDowFlag
    bool rcwFlag
    bool leftRctaFlag

    bool rightRctaFlag
    bool leftRctbFlag
    bool rightRctbFlag
    bool leftFctaFlag

    bool rightFctaFlag
    bool leftFctbFlag
    bool rightFctbFlag
	
    uint8 isSplit

    int8 objBsdWarningFlag
    int8 objLcaWarningFlag
    int8 objRctaWarningFlag
    int8 objDowWarningFlag

    int8 objRcwWarningFlag
    int8 objFctaWarningFlag
    int8 objRctbWarningFlag
    int8 objFctbWarningFlag
    float32 drawLength
    float32 drawWidth    


